### ISSUE TITLE
live video stopped working in current browsers

### ISSUE THREAD

**Issue by vcaputo** [motioneye-project/motioneye#2699]
I have some RPi Zero W cams running MotionEye I setup several years ago.

Everything worked great for ages but it seems at some point by keeping my desktops/laptops current, the latest browsers don't work with whatever MotionEye is using for the live video feeds.

These cameras are very slow and they're installed at a remote off-grid location having limited bandwidth.  So I'm quite averse to attempting a multi-day wholesale dist-upgrade and updating all the python deps+motioneye, esp. without even knowing it will resolve things. 

Is this an understood problem with an easy spot-fix I can do on the cameras to get the live feed back?

Everything else is still working, and I am still able to access the still images in the archives as well as receiving notifications.  But when I'm on-site it's quite useful to bring up the live feeds when I get a motion notification, and that no longer works.

Thanks in advance for any assistance, and apologies if this is a misuse of the issues section.  If there's a preferred space for such questions please refer me there and I'll close this!

MotionEye has been really great, it's just too bad the web seems utterly incapable of not constantly breaking itself.

**Comment by zagrim** [comment]
I don't know if you already ended up doing that, but "several years" old ME setup sounds like it has everything dated enough that it just might be that the current browsers have changed so that whatever the old video stream did is not anymore compatible. For example, we had this: #1428. Does that match what you are experiencing?
Unless that works, and unless you are able to find here a similar issue with a workaround, upgrade is likely the easiest solution.

**Comment by vcaputo** [comment]
Thanks, that indeed is the browser change affecting my cams.
