### ISSUE TITLE
netcam_url v4l2:///dev/dev0

### ISSUE THREAD

**Issue by JeepHu** [motioneye-project/motioneye#2836]
I've installed motioneye as per [these ](https://github.com/motioneye-project/motioneye/wiki/Install-on-Raspbian-Bullseye)instructions.
I'm on a RPI 4 and on Bullseye x64.
I tried to setup a usb very old webcam (OmniVision Technologies, Inc. OV511+ Webcam) from Creative.
When the image comes up, I can only see a grey screen with the setup overlay.
Looking on Google for the possible solution, I've found someone with the same problem and he was told to check with:
`netcam_url v4l2:///dev/dev3`
But when I type that command I get:
`-bash: netcam_url: command not found`

lsusb putput:
`Bus 002 Device 002: ID 174c:55aa ASMedia Technology Inc. ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge, ASM1153E SATA 6Gb/s bridge
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 05a9:a511 OmniVision Technologies, Inc. OV511+ Webcam
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

PS: should that be useful,  I installed Python 2.7 and set it up as the default Python because the tutorial I used said to to so

**Comment by zagrim** [comment]
I think the advice related to `netcam_url` referred to Motion camera configuration, and basically that configuration parameter `netcam_url v4l2:///dev/dev3` translates in MotionEye UI as having a network camera with URL `v4l2:///dev/dev3`. I don't quite understand why one would like to use network camera with such URL instead of configuring it directly as V4L2 camera with device `/dev/dev3` (which sounds odd, too, since I've understood that the device names tend to start with "video", e.g. `/dev/video3` but I've not been dealing with USB cameras so my experience is thin in this area).

But what you could do is to try out the current dev branch (still unreleased) using the instructions given in https://github.com/motioneye-project/motioneye/blob/dev/README.md (you likely should make Python 3 the default again). Should problems rise, please attach log file (see https://github.com/motioneye-project/motioneye/wiki/Troubleshooting#getting-the-log-file).

**Comment by JeepHu** [comment]
Hi zagrim, thank you for your answer.
I realise now it was my mistake. The [recommendation](https://github.com/Motion-Project/motion/discussions/1519) actually used "video" and not "dev".
I then checked on google and yes those were configuration strings in the conf file. I'm just beginning with Linux and Motion...
About the "url" setting, the three slashes refer to a local camera and not a protocol despite what it makes think. I've just learned ([here](https://motion-project.github.io/motion_config.html#netcam_url)) .
Anyway, in the meantime I've seen there's no driver for a webcam like mine, which uses "Pixel Format: 'O511' (GSPCA OV511)" as given by the command `sudo v4l2-ctl --device=/dev/video0 --all` .

For me to use the new branch, can I just update Motion without reinstalling everything and make Python3 the default one again?

Thank you again

> I think the advice related to `netcam_url` referred to Motion camera configuration, and basically that configuration parameter `netcam_url v4l2:///dev/dev3` translates in MotionEye UI as having a network camera with URL `v4l2:///dev/dev3`. I don't quite understand why one would like to use network camera with such URL instead of configuring it directly as V4L2 camera with device `/dev/dev3` (which sounds odd, too, since I've understood that the device names tend to start with "video", e.g. `/dev/video3` but I've not been dealing with USB cameras so my experience is thin in this area).
> 
> But what you could do is to try out the current dev branch (still unreleased) using the instructions given in https://github.com/motioneye-project/motioneye/blob/dev/README.md (you likely should make Python 3 the default again). Should problems rise, please attach log file (see https://github.com/motioneye-project/motioneye/wiki/Troubleshooting#getting-the-log-file).

**Comment by zagrim** [comment]
> For me to use the new branch, can I just update Motion without reinstalling everything and make Python3 the default one again?

You don't need to reinstall everything from scratch, but since the used Python version changes MotionEye files go to a different location during installation, so you can't really upgrade it but the installation instructions should still be fine. The configuration files stay in the same location and if needed they should get migrated to match the Motion version (if you upgrade that) as well as with whatever changes have been made for MotionEye in particular.

It might be enough to do basically just step 3 from the dev branch installation instructions, but given that the dependencies are not the same as for the old released version, it's best to run go through the apt install commands, too. If you are not using the latest available Motion, you can upgrade that first, then go on with the below commands:

```
sudo apt update
sudo apt --no-install-recommends install ca-certificates curl python3 python3-dev libcurl4-openssl-dev gcc libssl-dev

sudo systemctl stop motioneye
sudo python3 -m pip install 'https://github.com/motioneye-project/motioneye/archive/dev.tar.gz'
sudo motioneye_init
```

I'm assuming here that you do have `python3` and `pip3` available anyway.

**Comment by JeepHu** [comment]
Thank you zagrim. Honestly I didn't feel like testing that way, even though I firstly wanted to. I had an image of the system made before installing Python2 and that version of Motion and I restored that and installed the dev branch you told me.
In the meantime, a TP-Link Tapo C310 has arrived and I'm finally doing my tests. It is working great. I will take advantage of your help and the one of the others in case of issues.
Thanks again!

**Comment by zagrim** [comment]
Good to hear. In case everything related to this is now solved, please close this issue.

**Comment by JeepHu** [comment]
Thanks
