### ISSUE TITLE
thumbs are generated but not displayed in the preview

### ISSUE THREAD

**Issue by StefanWausH** [motioneye-project/motioneye#2873]
Hello everyone. I have Motioneye running on a RPI4 compute module together with the Dietpi distro and a network camera from Dahua connected. The thumbs of the individual videos are generated, but not displayed in the preview window. In earlier tests I had an original raspi-cam. Everything worked fine there.
Any ideas?
![Dashboard](https://github.com/motioneye-project/motioneye/assets/150660316/2b14713f-7450-4e49-928d-73b06e342426)
![Raspicam prev](https://github.com/motioneye-project/motioneye/assets/150660316/ea4134e3-3d63-40a4-a21b-ece01b7e03ec)

**Comment by zagrim** [comment]
How have you installed MotionEye? This looks like an issue with recent Pillow versions that was just fixed in the dev branch (Python3 support) and also in edge docker images.
So basically the fix should be to upgrade using the dev version by either following [these instuctions](https://github.com/motioneye-project/motioneye/blob/dev/README.md) or [edge image from here](https://github.com/motioneye-project/motioneye/pkgs/container/motioneye).

**Comment by StefanWausH** [comment]
The installation was carried out via the Dietpi distribution. https://dietpi.com/#home 
https://github.com/MichaIng is one of the developers. :) 
I tried it with Debian Bullseye as well as with the new Debian Bookworm version. The result is the same. And it already worked with it, which surprises me the most. I'll do the upgrade from your link again and report back. 
Thanks for your feedback for now

**Comment by StefanWausH** [comment]
It worked...creepy.
I probably did the right thing at the time, i.e. carried out the update.
Thanks for the tip and have a nice day!
Greetings, Stefan
