### ISSUE TITLE
motioneye not updating v4l2 camera size & fps.

### ISSUE THREAD

**Issue by adminy** [motioneye-project/motioneye#2941]
I tried rpicam-vid, everything works, can record in any camera supported resolution. Does not work in motioneye ui though ... same camera selected!
```js
[WRN] [ALL] motion_init: Could not fetch initial image from camera
[WRN] [ALL] motion_init: Motion continues using width and height from config file(s)
[WRN] [ALL] mlp_retry: Retrying until successful connection with camera
[ERR] [VID] v4l2_fps_set: Error setting fps. Return code -1
motion[1160]: [1:ml1:Camera1] [ERR] [VID] v4l2_mmap_set: Error starting stream. VIDIOC_STREAMON: Invalid argument
[ERR] [VID] vid_start: V4L2 device failed to open
kernel: unicam fe801000.csi: Wrong width or height 640x480 (remote pad set to 9152x6944)
kernel: unicam fe801000.csi: Failed to start media pipeline: -22
```

Looks like motioneye is sending only the desired camera size but its not actually doing a `v4l2-ctl -v` parameter setting command.

**Comment by zagrim** [comment]
Is this Pi camera 3? That requires libcamera support which is still somewhat open question for MotionEye. Motion requires using libcamerify in order to deal with those cameras, but integrating that to ME is still in progress. There have been some proposed workarounds, but some people have had issues with any of them. However, if you are feeling adventurous, see #2425 and the linked issues.

**Comment by adminy** [comment]
I just got a defective camera it seems.
